#!/usr/bin/env python3
"""Rebuild the quarantined character framework source from this repository's history.

The 2026-08-25 quarantine moved 513 files outside the project root and recorded
their SHA-256 digests but not their destination. Most of that payload is compiler
output; the authored source is 96 files totalling 209,178 bytes, and this history
still carries earlier revisions of every one of them.

This tool reconstructs what it can PROVE. For each file in the before-move
manifest it searches every blob that ever existed at that path across all
commits, applies the documented transformations that later sessions performed,
and writes the result only when its SHA-256 equals the recorded digest. A file
that cannot be matched is reported, never guessed at and never approximated from
a successor implementation.

Output goes outside the project root by default. Session 19 accepted the
framework's absence from the project tree
(``characterFrameworkExternalQuarantine.mustBeOutsideProjectRoot: true``), so
writing a rebuilt copy back inside would break the closure it granted. The result
is a reconstruction, not the quarantined originals, and the receipt says so.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = (
    ROOT / "Evidence/Session19"
    / "CharacterFrameworkBeforeMove-S19_Framework_20260825T031617Z_c68ee2e4e6be.tsv"
)
TRACKED_PREFIX = "Plugins/DiscGolfCharacterFramework"
MANIFEST_FIELDS = ("rootId", "relativePath", "bytes", "sha256")

# Session 9 replaced the framework's brand identifiers with generic ones. The
# exact strings are pinned by EXPECTED_GENERIC_SNIPPETS in
# Scripts/validate_dg_session9_brand_license.py, so this is a documented rewrite
# being replayed, not a guess at what changed.
SESSION9_BRAND_SUBSTITUTIONS = (
    (b"premium_disc_golf", b"dg_generic"),
    (b"premium_bag_default", b"dg_generic_bag_default"),
    (b"premium_default", b"dg_generic_default"),
)

# Compiler output. Regenerated by the first editor build; nothing in this
# repository could reconstruct it, and nothing should try.
DERIVED_PREFIXES = ("Binaries/", "Intermediate/")


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def read_manifest(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.reader(handle, delimiter="\t"))
    if rows and [cell.strip('"') for cell in rows[0]] == list(MANIFEST_FIELDS):
        rows = rows[1:]
    return [
        dict(zip(MANIFEST_FIELDS, [cell.strip('"') for cell in row]))
        for row in rows if len(row) >= len(MANIFEST_FIELDS)
    ]


def git(*args: str) -> str:
    done = subprocess.run(
        ["git", "-C", str(ROOT), *args],
        capture_output=True, text=True, check=True,
    )
    return done.stdout


def blob_bytes(blob: str) -> bytes:
    done = subprocess.run(
        ["git", "-C", str(ROOT), "cat-file", "blob", blob],
        capture_output=True, check=True,
    )
    return done.stdout


def collect_all_blobs(size_limit: int = 1024 * 1024) -> dict[str, tuple[str, str]]:
    """Index every small blob in the repository by the digest of each variant.

    Some files were renamed between the tracked copy and the quarantined one, so
    a path-scoped search misses them. This catches any file whose content ever
    existed anywhere in the history, under any documented transformation.
    """
    listing = git("cat-file", "--batch-all-objects",
                  "--batch-check=%(objectname) %(objecttype) %(objectsize)")
    index: dict[str, tuple[str, str]] = {}
    for line in listing.splitlines():
        parts = line.split()
        if len(parts) != 3 or parts[1] != "blob" or int(parts[2]) > size_limit:
            continue
        blob = parts[0]
        data = blob_bytes(blob)
        if data[:12] == b"version https":  # Git LFS pointer, not the content
            continue
        for label, form in candidates(data):
            index.setdefault(sha(form), (blob, label))
    return index


def collect_history() -> dict[str, list[str]]:
    """Map each historical plugin path to every blob it ever held, newest first."""
    commits = git("rev-list", "--all", "--", TRACKED_PREFIX).split()
    versions: dict[str, list[str]] = {}
    for commit in commits:
        listing = git("ls-tree", "-r", commit, "--", TRACKED_PREFIX)
        for line in listing.splitlines():
            meta, path = line.split("\t", 1)
            blob = meta.split()[2]
            slot = versions.setdefault(path, [])
            if blob not in slot:
                slot.append(blob)
    return versions


def candidates(data: bytes):
    """Yield (label, bytes) for each documented transformation of a blob.

    Line-ending variants are included because .gitattributes normalizes text on
    checkout, which changes a file's digest without changing its content.
    """
    swept = data
    for old, new in SESSION9_BRAND_SUBSTITUTIONS:
        swept = swept.replace(old, new)
    forms = [("verbatim", data)]
    if swept != data:
        forms.append(("session9-brand-sweep", swept))
    for label, form in list(forms):
        lf = form.replace(b"\r\n", b"\n")
        crlf = lf.replace(b"\n", b"\r\n")
        if lf != form:
            forms.append((f"{label}+lf", lf))
        if crlf != form:
            forms.append((f"{label}+crlf", crlf))
    return forms


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", type=Path, default=Path.home() / "DGTour_FrameworkReconstruction",
        help="destination directory; must be outside the project root",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="report what would be reconstructed without writing files",
    )
    args = parser.parse_args()

    out = args.out.resolve()
    if ROOT.resolve() in out.parents or out == ROOT.resolve():
        print(f"REFUSED: {out} is inside the project root.")
        print("Session 19 accepted the framework's absence from the project tree; "
              "writing it back inside would break that closure.")
        return 2

    if not MANIFEST.is_file():
        print(f"FAIL: manifest is missing: {MANIFEST}")
        return 2

    rows = read_manifest(MANIFEST)
    versions = collect_history()
    print(f"History holds {len(versions)} distinct plugin paths across "
          f"{sum(len(v) for v in versions.values())} blob revisions.")
    all_blobs = collect_all_blobs()
    print(f"Content index covers {len(all_blobs)} digests across every blob in "
          f"the repository.\n")

    rebuilt, unmatched, derived = [], [], []
    for row in rows:
        rel = row["relativePath"]
        if rel.startswith(DERIVED_PREFIXES):
            derived.append(row)
            continue
        want = row["sha256"].upper()
        match = None
        for blob in versions.get(f"{TRACKED_PREFIX}/{rel}", []):
            data = blob_bytes(blob)
            for label, form in candidates(data):
                if sha(form) == want:
                    match = (blob, label, form)
                    break
            if match:
                break
        if not match:
            # Fall back to a content search over the whole history, which finds
            # files that were renamed between the tracked and quarantined copies.
            found = all_blobs.get(want)
            if found:
                blob, label = found
                for candidate_label, form in candidates(blob_bytes(blob)):
                    if candidate_label == label:
                        match = (blob, f"{label} (content search)", form)
                        break
        if not match:
            unmatched.append(row)
            continue
        blob, label, form = match
        target = out / row["rootId"] / rel
        if not args.dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(form)
        rebuilt.append({
            "rootId": row["rootId"],
            "relativePath": rel,
            "bytes": len(form),
            "sha256": want,
            "sourceBlob": blob,
            "transformation": label,
        })

    authored = len(rows) - len(derived)
    print(f"Authored files in manifest: {authored}")
    print(f"  rebuilt and digest-verified: {len(rebuilt)}")
    print(f"  not reconstructible:         {len(unmatched)}")
    print(f"Derived build output skipped:  {len(derived)} "
          f"({sum(int(r['bytes']) for r in derived):,} bytes; "
          f"regenerated by an editor build)\n")

    by_transform: dict[str, int] = {}
    for entry in rebuilt:
        by_transform[entry["transformation"]] = (
            by_transform.get(entry["transformation"], 0) + 1)
    for label, count in sorted(by_transform.items()):
        print(f"  via {label}: {count}")

    if unmatched:
        print("\nNot reconstructible -- these carry edits made after the last "
              "revision this history contains:")
        for row in unmatched:
            print(f"  {row['rootId']}:{row['relativePath']} "
                  f"({int(row['bytes']):,} B recorded)")

    receipt = {
        "schema": "DiscGolfTour.CharacterFrameworkReconstruction.v1",
        "manifest": {
            "path": str(MANIFEST.relative_to(ROOT)).replace("\\", "/"),
            "sha256": sha(MANIFEST.read_bytes()),
            "rows": len(rows),
        },
        "authority": "RECONSTRUCTION_FROM_PUBLISHED_HISTORY_NOT_THE_QUARANTINED_ORIGINALS",
        "destination": str(out),
        "dryRun": args.dry_run,
        "authoredFiles": authored,
        "rebuiltVerified": len(rebuilt),
        "notReconstructible": [
            {"rootId": r["rootId"], "relativePath": r["relativePath"],
             "recordedBytes": int(r["bytes"]), "recordedSha256": r["sha256"].upper()}
            for r in unmatched
        ],
        "derivedSkipped": len(derived),
        "files": rebuilt,
    }
    if not args.dry_run:
        out.mkdir(parents=True, exist_ok=True)
        receipt_path = out / "reconstruction_receipt.json"
        receipt_path.write_text(json.dumps(receipt, indent=2), encoding="utf-8")
        print(f"\nWrote {len(rebuilt)} files to {out}")
        print(f"Receipt: {receipt_path}")
    else:
        print("\nDry run: nothing written.")

    return 0 if rebuilt and not unmatched else 1


if __name__ == "__main__":
    sys.exit(main())
